Loads mtls files when loading objs files.
elrnv/meshx pull request #8
Opened 2024-12-16 22:22 UTC by francocipollone

Related to https://github.com/elrnv/gltfgen/pull/9

### Summary

 - Adds support for mtl files when loading wavefront files.

2024-12-26 19:44 UTC, elrnv requested changes
Thank you for the PR!
I realized the error used here is for Msh type, which is distinct from Obj. So it would be more appropriate to use a new error type here. Could you add a new error type in obj.rs for `ObjError` right under `MissingMTLName` variant like so:
```
    /// Error loading associated `mtl` file.
    MtlLoadError {
        source: MtlLibsLoadError,
    },
```
and add an entry in the display trait like so:
```
            ObjError::MtlLoadError { source } => write!(f, "Error Loading mtl file: {source}",),
```
Then with the suggested changes it should work.

Thanks again!

2024-12-26 19:44 UTC, elrnv commented on src/io.rs
> +                    },
```
                source: MeshIOError::Obj {
                    source: obj::ObjError::MtlLoadError { source: e },
                },
```

2024-12-26 19:44 UTC, elrnv commented on src/io/msh.rs
> +    pub message: String,
Not needed with the other changes

2025-02-17 22:33 UTC, francocipollone commented on src/io/msh.rs
> +    pub message: String,
Done!

2025-02-17 22:33 UTC, francocipollone commented on src/io.rs
> +                    },
Done!

2025-02-17 22:33 UTC, francocipollone commented
Hey @elrnv thanks a lot for the comments, sorry for late response on my end, end of year + vacations kicked in :smile: .

PTAL and let me know if any further change is needed :rocket:

2025-03-27 14:21 UTC, francocipollone commented
Hey @elrnv , friendly ping in this PR. Let me know if there is something else to do :smile:

2025-03-31 04:00 UTC, elrnv approved these changes
Thank you for making these changes, looks great!

2025-03-31 04:01 UTC, merged